export interface MotivationalAd {
  id: number;
  image: string;
  title: string;
  description: string;
  cta: string;
}

export const motivationalAds: MotivationalAd[] = [
  {
    id: 1,
    image: "/ads/motivation1.jpg",
    title: "Persistence Pays Off",
    description: "Every 'no' gets you closer to a 'yes' — keep pushing.",
    cta: "Stay Consistent",
  },
  {
    id: 2,
    image: "/ads/motivation2.jpg",
    title: "Don't Back Down",
    description: "Great deals aren't accepted — they're earned through belief.",
    cta: "Push Forward",
  },
  {
    id: 3,
    image: "/ads/motivation3.jpg",
    title: "Win Them Over",
    description:
      "Clients don't always see the vision — until you show it with conviction.",
    cta: "Lead with Confidence",
  },
  {
    id: 4,
    image: "/ads/motivation4.jpg",
    title: "Keep Showing Up",
    description: "Success belongs to those who refuse to quit.",
    cta: "Try Again",
  },
  {
    id: 5,
    image: "/ads/motivation5.jpg",
    title: "Be the Difference",
    description: "Sometimes your belief is all the client needs to say yes.",
    cta: "Stand Firm",
  },
  {
    id: 6,
    image: "/ads/motivation6.jpg",
    title: "Relentless Energy",
    description: "Your passion will outlast their doubts.",
    cta: "Fuel the Fire",
  },
  {
    id: 7,
    image: "/ads/motivation7.jpg",
    title: "It’s Not Over",
    description: "Rejection is just redirection. Knock again.",
    cta: "Try Another Angle",
  },
  {
    id: 8,
    image: "/ads/motivation8.jpg",
    title: "The Power of Belief",
    description: "If you believe in what you’re offering, keep sharing it.",
    cta: "Believe Big",
  },
  {
    id: 9,
    image: "/ads/motivation9.jpg",
    title: "Turn Resistance Into Respect",
    description: "Respect is earned when you refuse to walk away.",
    cta: "Earn It",
  },
  {
    id: 10,
    image: "/ads/motivation10.jpg",
    title: "Conviction Wins",
    description: "Speak with conviction. People trust certainty.",
    cta: "Be Bold",
  },
  {
    id: 11,
    image: "/ads/motivation11.jpg",
    title: "One More Pitch",
    description: "Your next pitch could be the one they remember.",
    cta: "Go Again",
  },
  {
    id: 12,
    image: "/ads/motivation12.jpg",
    title: "Every Day Counts",
    description: "Small steps every day build unstoppable momentum.",
    cta: "Keep Building",
  },
  {
    id: 13,
    image: "/ads/motivation13.jpg",
    title: "You’re Almost There",
    description: "You may be just one conversation away from a breakthrough.",
    cta: "Don’t Stop",
  },
  {
    id: 14,
    image: "/ads/motivation14.jpg",
    title: "Prove the Value",
    description: "Don’t just sell — show why it matters.",
    cta: "Demonstrate",
  },
  {
    id: 15,
    image: "/ads/motivation15.jpg",
    title: "Persistence Overcomes Resistance",
    description: "Keep going until they can’t ignore you.",
    cta: "Break Through",
  },
  {
    id: 16,
    image: "/ads/motivation16.jpg",
    title: "Work the Vision",
    description: "Paint the picture so clearly they can’t unsee it.",
    cta: "Inspire",
  },
  {
    id: 17,
    image: "/ads/motivation17.jpg",
    title: "Outlast Doubt",
    description: "Let your commitment outlast their hesitation.",
    cta: "Stay In",
  },
  {
    id: 18,
    image: "/ads/motivation18.jpg",
    title: "Your Confidence Sells",
    description: "Confidence is contagious — share yours.",
    cta: "Be Sure",
  },
  {
    id: 19,
    image: "/ads/motivation19.jpg",
    title: "Speak With Passion",
    description: "Let your excitement do the convincing.",
    cta: "Spark Interest",
  },
  {
    id: 20,
    image: "/ads/motivation20.jpg",
    title: "Master the Follow-Up",
    description: "Polite persistence shows professionalism.",
    cta: "Follow Up",
  },
  {
    id: 21,
    image: "/ads/motivation21.jpg",
    title: "Overdeliver",
    description: "Show them you're already going above and beyond.",
    cta: "Go Further",
  },
  {
    id: 22,
    image: "/ads/motivation22.jpg",
    title: "Turn Setbacks Into Setups",
    description: "Every rejection sets you up for a better angle.",
    cta: "Reframe It",
  },
  {
    id: 23,
    image: "/ads/motivation23.jpg",
    title: "The Champion Mindset",
    description: "Champions persist when others walk away.",
    cta: "Think Like One",
  },
  {
    id: 24,
    image: "/ads/motivation24.jpg",
    title: "Vision Over Visibility",
    description: "Even when they don’t see it — you do.",
    cta: "Stay Focused",
  },
  {
    id: 25,
    image: "/ads/motivation25.jpg",
    title: "Earn Their Trust",
    description: "Consistency builds trust — one interaction at a time.",
    cta: "Be Consistent",
  },
  {
    id: 26,
    image: "/ads/motivation26.jpg",
    title: "Be Their Solution",
    description: "Solve real problems. Be irreplaceable.",
    cta: "Add Value",
  },
  {
    id: 27,
    image: "/ads/motivation27.jpg",
    title: "Outperform Expectations",
    description: "Let your effort speak louder than your pitch.",
    cta: "Surprise Them",
  },
  {
    id: 28,
    image: "/ads/motivation28.jpg",
    title: "Speak Their Language",
    description: "Tailor your offer to their real needs.",
    cta: "Connect Deeply",
  },
  {
    id: 29,
    image: "/ads/motivation29.jpg",
    title: "Own the Outcome",
    description: "Take responsibility for making it work.",
    cta: "Take Charge",
  },
  {
    id: 30,
    image: "/ads/motivation30.jpg",
    title: "Clients Want Leaders",
    description: "Lead the conversation, guide the solution.",
    cta: "Lead Clearly",
  },
  {
    id: 31,
    image: "/ads/motivation31.jpg",
    title: "Make It Personal",
    description: "People say yes to people they trust.",
    cta: "Build Rapport",
  },
  {
    id: 32,
    image: "/ads/motivation32.jpg",
    title: "Don’t Sell. Empower.",
    description: "Empower them to make a smart choice.",
    cta: "Educate",
  },
  {
    id: 33,
    image: "/ads/motivation33.jpg",
    title: "See It Through",
    description: "Most give up too soon — you won’t.",
    cta: "Stay the Course",
  },
  {
    id: 34,
    image: "/ads/motivation34.jpg",
    title: "Trust the Process",
    description: "What you're building takes time — and it's worth it.",
    cta: "Keep Going",
  },
  {
    id: 35,
    image: "/ads/motivation35.jpg",
    title: "This Is Your Moment",
    description: "Act like the win is already yours — because it is.",
    cta: "Own It",
  },
];
